### ISSUE TITLE
[Bug] Mystical World's Charred Wood have block but not ItemBlock, cause recipe to use no ingredient

### ISSUE THREAD

**Issue by KorewaLidesu** [CaliforniaDemise/Backportium#1]
![image](https://github.com/user-attachments/assets/2391a87e-0a99-416b-ae93-577d7e73be08)
![image](https://github.com/user-attachments/assets/17681917-4610-4d1a-b4fa-a21ad088eb1e)
![image](https://github.com/user-attachments/assets/6fcff5b7-b6c7-49c8-b65e-469342cc5511)

**Comment by CaliforniaDemise** [comment]
Fixed in dev.
